# Generated by Django 6.0.2 on 2026-02-16 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='endereço',
            new_name='endereco',
        ),
    ]
