# Generated by Django 6.0.2 on 2026-02-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_endereço_cliente_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='preco_frete',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
