# Generated by Django 6.0.2 on 2026-02-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_carga_preco_frete'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='acompanhada',
            field=models.BooleanField(default=False, verbose_name='Cliente vai acompanhar a carga?'),
        ),
        migrations.AddField(
            model_name='carga',
            name='categoria',
            field=models.CharField(choices=[('construcao', 'Materiais de Construção'), ('mobilia', 'Mobiliário/Casa'), ('eletro', 'Eletrodomésticos'), ('outros', 'Outros/Diversos')], default='outros', max_length=20),
        ),
        migrations.AddField(
            model_name='carga',
            name='data_agendamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Agendamento'),
        ),
        migrations.AddField(
            model_name='carga',
            name='destino_coords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Coordenadas de Destino (lat,long)'),
        ),
        migrations.AddField(
            model_name='carga',
            name='origem_coords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Coordenadas de Origem (lat,long)'),
        ),
        migrations.AddField(
            model_name='carga',
            name='tipo_servico',
            field=models.CharField(choices=[('IMEDIATO', 'Serviço Imediato'), ('AGENDADO', 'Serviço Agendado')], default='IMEDIATO', max_length=20, verbose_name='Tipo de Serviço'),
        ),
        migrations.AlterField(
            model_name='carga',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_TRANSITO', 'Em Trânsito'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20),
        ),
    ]
