# Generated by Django 6.0.2 on 2026-02-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_carga_acompanhada_carga_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='data_entrega',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrega'),
        ),
    ]
