# Generated by Django 6.0.2 on 2026-03-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pushtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='motoristas_recusaram',
            field=models.ManyToManyField(blank=True, related_name='cargas_recusadas', to='api.motorista'),
        ),
    ]
