# Generated by Django 6.0.2 on 2026-03-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_carga_motoristas_recusaram'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='bi_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='motorista',
            name='carta_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='motorista',
            name='foto_bi',
            field=models.ImageField(blank=True, null=True, upload_to='documentos/bi/'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='foto_carta',
            field=models.ImageField(blank=True, null=True, upload_to='documentos/cartas/'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='foto_placa',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/placas/'),
        ),
    ]
