# Generated by Django 6.0.2 on 2026-03-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_motorista_bi_verificado_motorista_carta_verificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/clientes/'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/motoristas/'),
        ),
    ]
